dvsa/mes-data-poller-service

- destination-db/converted-queries.sql
- destination-db/schema.sql
- dms-configurator/src/cli-app.ts
Added time windows to cli-app.ts
Expanded time windows in converted-queries.sql
(updated timings are on confluence)
> Expanded time windows

- dms-configurator/src/cli-app.ts
- dms-configurator/src/dms.ts
- dms-configurator/src/table-mapping.ts
- table-mappings/application-tables.json
- table-mappings/examiner-tables.json
- table-mappings/other-tables.json
- table-mappings/slot-tables.json
- table-mappings/slotdetail-tables.json
DMS changes from full-load to full-load-and-cdc including new endpoints, replication instance and database name
> DMS Changes for CDC Mode

- dms-configurator/package.json
- dms-configurator/src/cli-app.ts
- dms-configurator/src/dms.ts
- dms-configurator/src/table-mapping.spec.ts
- dms-configurator/src/table-mapping.ts
- dms-configurator/src/util.ts
- dms-configurator/tslint.json
**Ignore whitespace strongly recommended when viewing diff**
tslint seems to trigger nested `tslint.json` files in our CI build.
Fixing issues in DMS configurator that were causing lint to fail.
> Fix lint issues in DMS configurator

- package-lock.json
- package.json
> Fix security vulnerability by upgrading node.extend to 1.1.7

- destination-db/schema.sql
- dms-configurator/src/cli-app.ts
- table-mappings/static-tables.json
Also some formatting / tidying of existing schema objects.
> Schema and mapping changes for extended test data items

- src/functions/pollJournals/framework/repo/mysql/non-test-activity-repository.ts
- src/functions/pollJournals/framework/repo/mysql/row-mappers/__tests__/test-slot-row-mapper.spec.ts
- src/functions/pollJournals/framework/repo/mysql/row-mappers/test-slot-row-mapper.ts
- src/functions/pollJournals/framework/repo/mysql/test-slot-repository.ts
- exclude all null or empty fields from Journal JSON
- treat zero-length or whitespace strings as empty in row mapper
- simplify Test Slot query, remove NULLIF(..)
- checked all other queries, fixed non-test-activities which shouldn't be left join 
- [*] [WIP] tag removed from PR title
- [*] PR has an understandable description
- [*] branch name comply with our branching strategy
- [*] git branch contains relevant JIRA ticket number
- [*] branch rebased against the latest develop
- [*] Code has been tested manually
- [*] Reviewers selected in Github
- [*] PR link added to JIRA
> MES-1727 Exclude null or empty fields from Journal JSON

- src/functions/pollJournals/framework/repo/dynamodb/__tests__/journal-repository.spec.ts
- src/functions/pollJournals/framework/repo/dynamodb/journal-repository.ts
* Sequence journal save batchWrite requests instead of submitting concurrently to reduce failures
* Ensure hashes for all examiners are returned from DDB table scan by using the `LastEvaluatedKey` on the response to submit additional scans if necessary
> Fix issues with Journal poller DynamoDB interaction

- destination-db/schema.sql
Another covering index to improve performance of advanced-test-slot query (and all other queries that use work_schedule_slots). Confirmed by performance testing on "perf".
- [*] [WIP] tag removed from PR title
- [*] PR has an understandable description
- [*] branch name comply with our branching strategy
- [*] git branch contains relevant JIRA ticket number
- [*] branch rebased against the latest develop
- [*] Code has been tested manually
> MES-1832: Added PROGRAMME_SLOT covering index

- src/functions/updateDmsTaskWithDates/framework/config/config.ts
- src/functions/updateDmsTaskWithDates/framework/config/task-settings.ts
MES-1802
- Enables DMS Task loggin
- Removes option to set via config/environment variable
> Enable DMS Task logging

- .gitignore
- package-lock.json
- package.json
> MES-1647 added test coverage script

- src/functions/pollJournals/application/transfer-datasets.ts
- src/functions/pollJournals/framework/config/__mocks__/config.ts
- src/functions/pollJournals/framework/config/config.ts
- src/functions/updateDmsTaskWithDates/framework/task-modifier.ts
> Mes 1797 - Make start date configurable for time travel testing

- src/functions/pollJournals/framework/config/config.ts
- src/functions/pollUsers/framework/config.ts
Generate config with each invocation so that the IAM RDS auth does not timeout.
> Generate configuration on each invocation to stop password timeout

- src/functions/pollJournals/framework/repo/mysql/pool.ts
- src/functions/pollUsers/framework/repo/mysql/examiner-repository.ts
Fixes journal poller issues on fresh RDS
> Set charset to use on db connections

- README.md
- destination-db/post-data-load/createPollerUser.sql
Made Poller user creation script reusable
Updated README
> Add context for new MySQL scripts

- package-lock.json
- package.json
- src/functions/pollJournals/framework/repo/mysql/test-slot-repository.ts
Install latest Journal schema dependency version
Remove duplicate column from test slot query
> Update Journal Schema Version

- src/functions/pollJournals/application/transfer-datasets.ts
- src/functions/pollJournals/framework/repo/dynamodb/journal-repository.ts
- src/functions/pollUsers/framework/repo/dynamodb/cached-examiner-repository.ts
> Mes 1866 custom metrics

- .secignore
- destination-db/pre-dms/010_applyLanguageSettings.sql
Add language settings script
Update .secignore
> Add database language settings

- src/functions/pollJournals/application/transfer-datasets.ts
- src/functions/pollJournals/framework/repo/mysql/test-slot-repository.ts
Add journalStartDate parameter
Change test slot query window to use journalStartDate
> Extend Journal Poller Window

- src/functions/pollJournals/application/__tests__/transfer-datasets.spec.ts
- src/functions/pollJournals/application/journal-builder.ts
- src/functions/pollJournals/domain/examiner-record.ts
- src/functions/pollJournals/framework/repo/mysql/examiner-repository.ts
- src/functions/pollJournals/framework/repo/mysql/row-mappers/test-slot-row-mapper.ts
* Ensure test slot row mapper helper field names are bound by the journal schema
* Better type safety around querying of examiners and building ExaminerWorkSchedule
> MES-2589: Improve type safety in accordance with journal schema

- src/functions/pollJournals/framework/repo/dynamodb/journal-repository.ts
MES-2862 - Increase poller self timeout to 2 minutes
> MES-2862 Increase timeout for 2 week lookback

- destination-db/database-objects/030_createIndexes.sql
* Add covering secondary index on ETHNIC_ORIGIN table to improve test slot query performance
> MES-2917: Index ETHNIC_ORIGIN table to improve test slot query performance

- src/functions/pollJournals/framework/repo/dynamodb/journal-repository.ts
> Revert journal poller DDB pollerFrequency variable back to 120s

- serverless.yml
- src/common/application/models/staff-details.ts
- src/functions/pollUsers/domain/__tests__/examiner-cache-reconciler.spec.ts
- src/functions/pollUsers/domain/__tests__/transfer-users.spec.ts
- src/functions/pollUsers/domain/constants/examiner-roles.ts
- src/functions/pollUsers/framework/repo/mysql/examiner-repository.ts
- Updating `StaffDetail` property `isLDTM` => `role`
> Updating StaffDetail property from isLDTM:boolean to role:string

- destination-db/sample-data-load/030_GenerateCalendarData.sql
* Ensure that we can start cat B tests when using the MySQL sample datasets
> MES-2269: Add MySQL sample load data that allows cat B tests from 2019 onwards

- src/functions/pollJournals/framework/repo/dynamodb/journal-repository.ts
> polling frequency increased to 3 minutes
